# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: smago <smago@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/13 12:53:22 by smago             #+#    #+#              #
#    Updated: 2021/03/13 12:55:45 by smago            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = Data.cpp main.cpp

NAME = serialize

all:
	clang++ -Wall -Wextra -Werror -std=c++98 $(SRCS) -o $(NAME)

clean:
	rm -f $(NAME)

